wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  networks:
    - wordpress-net

wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: back2skl
  ports:
    - 3306:3306
  networks:
    - wordpress-net

networks:
  wordpress-net:
    driver: bridge