version: "2"
services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8080:80
    networks:
      - wordpress-net

  wordpress_db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: asdf1234
    ports:
      - 3306:3306
    networks:
      - wordpress-net

networks:
  wordpress-net:
    driver: bridge
